version: '3'

services:
  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    container_name: inventory-app
    restart: always
    volumes:
      - .:/var/www/html
    environment:
      - PHP_FPM_LARAVEL=true
    networks:
      - inventory-net
    depends_on:
      - db
      - redis

  # Nginx Service
  web:
    image: nginx:alpine
    container_name: inventory-nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - inventory-net

  # MySQL Service
  db:
    image: linuxserver/mariadb:10.5.16-alpine
    container_name: inventory-mysql
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_USER: ${DB_USERNAME}
        MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker/data:/var/lib/mysql
    networks:
      - inventory-net
    ports:
      - "3306:3306"

  # Redis Service
  redis:
    image: redis:alpine
    container_name: inventory-redis
    restart: always
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ./docker/redis/config/redis.conf:/usr/local/etc/redis/redis.conf
      - ./docker/redis/data:/data
    networks:
      - inventory-net
    ports:
      - "6379:6379"

networks:
  inventory-net:
    driver: bridge

volumes:
  mysql-data:
